[[main]]
none = "none"

[[main]]
#pre = "codepen"
name = "Blog"
pageRef = "posts"
identifier = "rbOqdYeYfa"
weight = 9999

[[main]]
name = "Discografia"
pageRef = "discog"
identifier = "ccp90jbxcr"
weight = 9999

[[footer]]
none = "none"
