# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.


[[main]]
  #name = "Home"
  pre = "house-solid"
  pageRef = "/"
  weight = 9

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Music"
  pageRef = "discog"
  weight = 20

[[main]]
  name = "Album"
  pageRef = "tags/Album"
  weight = 21

[[main]]
  name = "Press"
  pageRef = "press"
  weight = 22

[[main]]
  identifier = "youtube"
  pre = "youtube"
  url = "https://www.youtube.com/@radiostarschannel"
  weight = 50

[[main]]
  identifier = "spotify"
  pre = "spotify"
  url = "https://open.spotify.com"
  weight = 50

[[main]]
  identifier = "jamendo"
  pre = "jamendo"
  url = "https://www.jamendo.com/artist/339872/the-radiostars"
  weight = 55

[[main]]
  identifier = "facebook"
  pre = "facebook"
  url = "https://www.facebook.com/profile.php?id=100067201026057"
  weight = 60

[[main]]
  identifier = "flickr"
  pre = "flickr"
  url = "https://www.flickr.com/photos/radiostars/"
  weight = 60

[[main]]
  identifier = "x-twitter"
  pre = "x-twitter"
  url = "https://www.x.com/theradiostars"
  weight = 99

#[[main]]
#  name = "Parent"
#  weight = 20

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "Live"
#  pageRef = "tags/live"
#  weight = 100

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
